[package]
name = "jiwonz/koact"
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
description = "React-like UI Framework for Roblox"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
