[package]
name = "jiwonz/koact"
version = "0.2.2"
registry = "https://github.com/UpliftGames/wally-index"
description = "React-like UI Framework for Roblox"
realm = "shared"
exclude = ["**"]
include = [
	"src",
	"src/**",
	"default.project.json",
	"LICENSE",
	"wally.toml"
]
license = "MIT"

[dependencies]
promise = "evaera/promise@4.0.0"
signal = "sleitnick/signal@2.0.1"
